In [64]:
import kagglehub


path = kagglehub.dataset_download("tobiasbueck/multilingual-customer-support-tickets")

print("Path to dataset files:", path)

Path to dataset files: /home/hello/.cache/kagglehub/datasets/tobiasbueck/multilingual-customer-support-tickets/versions/14

In [87]:
import pandas as pd 

df = pd.read_csv("data/aa_dataset-tickets-multi-lang-5-2-50-version.csv")
df.head(2)

,subject,body,answer,type,queue,priority,language,version,tag_1,tag_2,tag_3,tag_4,tag_5,tag_6,tag_7,tag_8
0,Wesentlicher Sicherheitsvorfall,"Sehr geehrtes Support-Team,\n\nich möchte eine...",Vielen Dank für die Meldung des kritischen Sic...,Incident,Technical Support,high,de,51,Security,Outage,Disruption,Data Breach,NaN,NaN,NaN,NaN
1,Account Disruption,"Dear Customer Support Team,\n\nI am writing to...","Thank you for reaching out, <name>. We are awa...",Incident,Technical Support,high,en,51,Account,Disruption,Outage,IT,Tech Support,NaN,NaN,NaN

In [88]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 28587 entries, 0 to 28586
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   subject   24749 non-null  str
 1   body      28587 non-null  str
 2   answer    28580 non-null  str
 3   type      28587 non-null  str
 4   queue     28587 non-null  str
 5   priority  28587 non-null  str
 6   language  28587 non-null  str
 7   version   28587 non-null  int64
 8   tag_1     28587 non-null  str
 9   tag_2     28574 non-null  str
 10  tag_3     28451 non-null  str
 11  tag_4     25529 non-null  str
 12  tag_5     14545 non-null  str
 13  tag_6     5874 non-null   str
 14  tag_7     2040 non-null   str
 15  tag_8     565 non-null    str
dtypes: int64(1), str(15)
memory usage: 3.5 MB

In [89]:
df.shape

(28587, 16)

In [90]:
df["language"].value_counts()

language
en    16338
de    12249
Name: count, dtype: int64

In [91]:
df.isnull().sum()

subject      3838
body            0
answer          7
type            0
queue           0
priority        0
language        0
version         0
tag_1           0
tag_2          13
tag_3         136
tag_4        3058
tag_5       14042
tag_6       22713
tag_7       26547
tag_8       28022
dtype: int64

In [92]:
df["subject"] = df["subject"].fillna("")

In [93]:
df = df.dropna(subset=['body'])

In [96]:
df = df[df["language"]== "en"]

In [97]:
df["text"] = df["subject"]+" "+df["body"]

In [98]:
df.isnull().sum()

subject         0
body            0
answer          3
type            0
queue           0
priority        0
language        0
version         0
tag_1           0
tag_2           6
tag_3          69
tag_4        1711
tag_5        7922
tag_6       12968
tag_7       15204
tag_8       16057
text            0
dtype: int64

In [99]:
df = df[["text", 'queue','type']] 
df

,text,queue,type
1,"Account Disruption Dear Customer Support Team,...",Technical Support,Incident
2,Query About Smart Home System Integration Feat...,Returns and Exchanges,Request
3,Inquiry Regarding Invoice Details Dear Custome...,Billing and Payments,Request
4,Question About Marketing Agency Software Compa...,Sales and Pre-Sales,Problem
5,"Feature Query Dear Customer Support,\n\nI hope...",Technical Support,Request
...,...,...,...
28578,Problem with Billing Adjustment An unexpected ...,Billing and Payments,Incident
28580,Urgent: Incident Involving Data Breach in Medi...,Product Support,Problem
28582,Performance Problem with Data Analytics Tool T...,Technical Support,Incident
28585,Update Request for SaaS Platform Integration F...,IT Support,Change
28586,Inquiry About Project Management Features Look...,Technical Support,Request

In [100]:
df.rename(
    columns = {
        'queue':'category',
        'type':"issuse_type"
    },inplace = True
)

In [101]:
df

,text,category,issuse_type
1,"Account Disruption Dear Customer Support Team,...",Technical Support,Incident
2,Query About Smart Home System Integration Feat...,Returns and Exchanges,Request
3,Inquiry Regarding Invoice Details Dear Custome...,Billing and Payments,Request
4,Question About Marketing Agency Software Compa...,Sales and Pre-Sales,Problem
5,"Feature Query Dear Customer Support,\n\nI hope...",Technical Support,Request
...,...,...,...
28578,Problem with Billing Adjustment An unexpected ...,Billing and Payments,Incident
28580,Urgent: Incident Involving Data Breach in Medi...,Product Support,Problem
28582,Performance Problem with Data Analytics Tool T...,Technical Support,Incident
28585,Update Request for SaaS Platform Integration F...,IT Support,Change
28586,Inquiry About Project Management Features Look...,Technical Support,Request

In [102]:
df['category'].value_counts()

category
Technical Support                  4737
Product Support                    3073
Customer Service                   2410
IT Support                         1942
Billing and Payments               1595
Returns and Exchanges               820
Service Outages and Maintenance     664
Sales and Pre-Sales                 513
Human Resources                     348
General Inquiry                     236
Name: count, dtype: int64

It was little bit imbalance , lets deal with it later

In [103]:
df.isnull().sum()

text           0
category       0
issuse_type    0
dtype: int64

In [104]:
df['text_length'] = df['text'].apply(len)
df['text_length'].mean()

np.float64(405.5386828253152)

In [105]:
df['text_length'] = df['text'].apply(lambda x: len(x.split()))
print(df['text_length'].mean())

58.64304076386339

In [106]:
df['text'].sample(5)

4156     Revise Support for Integration Updates Draftin...
23195    SAP Data Security Customer Support, seeking gu...
4759     Potential Data Breach at Healthcare Provider A...
11229    Problem with System Down Today Dear Support Te...
7862     Examining Delays in Loading Project Dashboards...
Name: text, dtype: str

In [107]:
from collections import Counter
all_words = " ".join(df['text']).lower().split()
Counter(all_words).most_common(40)

[('the', 42354),
 ('to', 37197),
 ('and', 30479),
 ('data', 12445),
 ('in', 12123),
 ('for', 12065),
 ('i', 11260),
 ('a', 10618),
 ('you', 10553),
 ('on', 10033),
 ('with', 9359),
 ('we', 9113),
 ('this', 8913),
 ('would', 8286),
 ('our', 7687),
 ('your', 7586),
 ('of', 7470),
 ('is', 7408),
 ('have', 7217),
 ('be', 7020),
 ('could', 6733),
 ('issue', 6047),
 ('customer', 5835),
 ('security', 5804),
 ('are', 5648),
 ('assistance', 5267),
 ('provide', 5238),
 ('appreciate', 5224),
 ('am', 4963),
 ('that', 4946),
 ('software', 4904),
 ('due', 4800),
 ('as', 4751),
 ('digital', 4722),
 ('medical', 4709),
 ('analytics', 4623),
 ('investment', 4549),
 ('support', 4338),
 ('please', 4321),
 ('about', 4299)]

In [108]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
import re

all_stop_words = ENGLISH_STOP_WORDS.union(['hi', 'hello', 'thanks', 'thank', 'regards', 'dear'])

In [127]:
def remove_stopwords(text):
    text = text.lower()
    text = re.sub(r"[^a-zA-Z]"," ",text)
    words = text.split()
    words = [w for w in words if w not in all_stop_words and len(w) > 2]
    return " ".join(words)

df["clean_text"] = df['text'].apply(remove_stopwords)
df['clean_text']

1        account disruption writing report significant ...
2        query smart home integration features hope mes...
3        inquiry regarding invoice details hope message...
4        question marketing agency software compatibili...
5        feature query hope message reaches good health...
                               ...
28578    billing adjustment unexpected billing discrepa...
28580    urgent incident involving breach medical recor...
28582    performance analytics tool analytics tool expe...
28585    update saas platform integration features requ...
28586    inquiry project management features detailed p...
Name: clean_text, Length: 16338, dtype: str

In [119]:
df

,text,category,issuse_type,text_length,clean_text
1,"Account Disruption Dear Customer Support Team,...",Technical Support,Incident,84,account disruption customer support team n ni ...
2,Query About Smart Home System Integration Feat...,Returns and Exchanges,Request,83,query smart home integration features customer...
3,Inquiry Regarding Invoice Details Dear Custome...,Billing and Payments,Request,95,inquiry regarding invoice details customer sup...
4,Question About Marketing Agency Software Compa...,Sales and Pre-Sales,Problem,103,question marketing agency software compatibili...
5,"Feature Query Dear Customer Support,\n\nI hope...",Technical Support,Request,99,feature query customer support n ni hope messa...
...,...,...,...,...,...
28578,Problem with Billing Adjustment An unexpected ...,Billing and Payments,Incident,21,problem billing adjustment unexpected billing ...
28580,Urgent: Incident Involving Data Breach in Medi...,Product Support,Problem,21,urgent incident involving data breach medical ...
28582,Performance Problem with Data Analytics Tool T...,Technical Support,Incident,16,performance problem data analytics tool data a...
28585,Update Request for SaaS Platform Integration F...,IT Support,Change,48,update request saas platform integration featu...
28586,Inquiry About Project Management Features Look...,Technical Support,Request,84,inquiry project management features looking de...

ok... Lets find Keywords belonging to the category

In [ ]:
def find_keywords():
    for item in df['category'].unique():
        print(f"Category : {item}")
        subset = df[df['category']== item]
        words = " ".join(subset['clean_text']).lower().split()
        common = Counter(words).most_common(60)
        print(common)
        # print("\n")

find_keywords()

There are many corpus-level stopwords.

In [123]:
custom_stopwords = set([
    'data','support','issue','issues','information','provide','request',
    'assistance','customer','appreciate','regards','thanks','thank',
    'dear','team','help','looking','forward','greatly','soon','problem','greatly','great','problems'
])

all_stop_words = ENGLISH_STOP_WORDS.union(custom_stopwords)

In [124]:
df["clean_text"] = df['text'].apply(remove_stopwords)
df['clean_text']

1        account disruption n ni writing report signifi...
2        query smart home integration features n ni hop...
3        inquiry regarding invoice details n ni hope me...
4        question marketing agency software compatibili...
5        feature query n ni hope message reaches good h...
                               ...
28578    billing adjustment unexpected billing discrepa...
28580    urgent incident involving breach medical recor...
28582    performance analytics tool analytics tool expe...
28585    update saas platform integration features requ...
28586    inquiry project management features detailed p...
Name: clean_text, Length: 16338, dtype: str

In [128]:
find_keywords()

Category : Technical Support
[('software', 2206), ('security', 1862), ('analytics', 1442), ('medical', 1367), ('integration', 1327), ('resolve', 1260), ('digital', 1169), ('investment', 1152), ('recent', 1107), ('marketing', 1105), ('project', 1085), ('updates', 1047), ('tools', 1036), ('matter', 1014), ('access', 1010), ('platform', 1001), ('systems', 945), ('management', 918), ('saas', 861), ('restarting', 860), ('guidance', 845), ('breach', 793), ('performance', 786), ('persists', 730), ('despite', 727), ('steps', 721), ('hospital', 717), ('network', 697), ('server', 693), ('possible', 672), ('strategies', 664), ('devices', 654), ('look', 621), ('resolving', 621), ('solution', 602), ('efforts', 573), ('need', 572), ('facing', 559), ('potential', 558), ('brand', 538), ('know', 524), ('attempts', 488), ('measures', 485), ('updating', 485), ('cause', 483), ('update', 480), ('troubleshooting', 468), ('compatibility', 458), ('impacting', 458), ('integrating', 448), ('incident', 448), ('report', 447), ('unauthorized', 446), ('outdated', 433), ('additional', 429), ('needed', 428), ('optimization', 428), ('attempted', 426), ('services', 419), ('settings', 418)]
Category : Returns and Exchanges
[('investment', 348), ('security', 348), ('software', 312), ('analytics', 263), ('medical', 257), ('digital', 240), ('integration', 228), ('marketing', 228), ('strategies', 198), ('management', 197), ('project', 191), ('brand', 187), ('saas', 151), ('guidance', 145), ('recent', 144), ('tools', 141), ('access', 141), ('matter', 139), ('platform', 138), ('engagement', 131), ('resolve', 129), ('products', 123), ('hospital', 122), ('look', 122), ('outdated', 118), ('details', 117), ('systems', 117), ('enhance', 116), ('optimization', 111), ('update', 110), ('services', 109), ('performance', 108), ('returns', 106), ('measures', 106), ('growth', 105), ('efforts', 105), ('updates', 103), ('campaign', 101), ('steps', 100), ('ensure', 100), ('breach', 97), ('campaigns', 96), ('features', 95), ('know', 95), ('despite', 94), ('healthcare', 94), ('detailed', 92), ('protocols', 92), ('product', 88), ('improve', 88), ('interested', 87), ('sensitive', 87), ('regarding', 85), ('potential', 79), ('time', 75), ('patient', 74), ('resolving', 73), ('like', 72), ('solution', 72), ('seeking', 72)]
Category : Billing and Payments
[('billing', 1691), ('payment', 772), ('details', 508), ('services', 496), ('security', 488), ('look', 460), ('medical', 410), ('available', 383), ('digital', 375), ('matter', 367), ('analytics', 361), ('saas', 343), ('options', 339), ('investment', 325), ('marketing', 313), ('software', 313), ('integration', 313), ('products', 312), ('strategies', 302), ('management', 300), ('discrepancies', 299), ('recent', 292), ('know', 282), ('detailed', 280), ('tools', 258), ('project', 254), ('resolve', 251), ('additionally', 243), ('reaching', 240), ('subscription', 237), ('update', 232), ('interested', 228), ('plans', 228), ('pricing', 228), ('brand', 224), ('hearing', 224), ('like', 223), ('guidance', 219), ('possible', 210), ('account', 208), ('additional', 207), ('access', 201), ('discounts', 200), ('methods', 195), ('inquiry', 192), ('charges', 191), ('process', 186), ('hospital', 177), ('response', 172), ('solution', 171), ('ensure', 167), ('platform', 166), ('seeking', 163), ('invoice', 161), ('time', 160), ('regarding', 159), ('including', 159), ('error', 159), ('inquire', 159), ('let', 151)]
Category : Sales and Pre-Sales
[('integration', 219), ('security', 196), ('strategies', 182), ('medical', 179), ('analytics', 174), ('saas', 172), ('digital', 172), ('management', 162), ('brand', 161), ('marketing', 156), ('project', 147), ('investment', 137), ('details', 136), ('solutions', 124), ('tools', 123), ('platform', 115), ('features', 110), ('growth', 99), ('services', 97), ('enhance', 97), ('software', 96), ('interested', 94), ('like', 86), ('reaching', 84), ('products', 84), ('detailed', 83), ('hospital', 83), ('know', 82), ('additionally', 81), ('update', 81), ('improve', 75), ('inquire', 70), ('access', 70), ('insights', 66), ('guidance', 64), ('engagement', 64), ('available', 62), ('compatibility', 61), ('financial', 60), ('options', 59), ('capabilities', 59), ('ensure', 59), ('potential', 58), ('measures', 58), ('optimize', 57), ('campaigns', 57), ('systems', 56), ('product', 56), ('optimization', 54), ('protocols', 53), ('pricing', 53), ('solution', 53), ('seeking', 53), ('time', 53), ('look', 53), ('meet', 52), ('various', 52), ('regarding', 51), ('inquiry', 51), ('sales', 50)]
Category : Service Outages and Maintenance
[('service', 485), ('medical', 226), ('digital', 226), ('outage', 218), ('network', 206), ('impacting', 205), ('outages', 201), ('tools', 193), ('software', 187), ('disruptions', 175), ('security', 175), ('server', 174), ('resolve', 168), ('analytics', 167), ('services', 166), ('matter', 157), ('marketing', 155), ('affected', 148), ('updates', 141), ('update', 140), ('recent', 139), ('systems', 136), ('disruption', 130), ('possible', 129), ('products', 129), ('access', 128), ('look', 112), ('maintenance', 103), ('cause', 101), ('saas', 100), ('management', 100), ('multiple', 97), ('project', 97), ('investment', 97), ('applications', 97), ('guidance', 93), ('platform', 92), ('overload', 92), ('financial', 92), ('brand', 92), ('steps', 89), ('restarting', 89), ('devices', 88), ('operations', 87), ('affecting', 87), ('solution', 86), ('currently', 83), ('strategy', 81), ('know', 79), ('hospital', 79), ('enhance', 78), ('downtime', 78), ('agency', 78), ('troubleshooting', 77), ('urgent', 77), ('interruptions', 76), ('critical', 76), ('unexpected', 76), ('performance', 76), ('initial', 75)]
Category : Product Support
[('security', 1229), ('analytics', 1025), ('software', 1021), ('integration', 990), ('digital', 990), ('investment', 963), ('marketing', 881), ('medical', 853), ('brand', 673), ('tools', 672), ('resolve', 667), ('strategies', 662), ('project', 640), ('recent', 625), ('access', 591), ('systems', 559), ('matter', 557), ('guidance', 548), ('management', 539), ('updates', 508), ('saas', 490), ('engagement', 480), ('performance', 464), ('despite', 457), ('efforts', 457), ('look', 431), ('hospital', 427), ('platform', 417), ('growth', 409), ('campaigns', 393), ('enhance', 382), ('campaign', 378), ('optimization', 360), ('steps', 358), ('possible', 354), ('products', 343), ('update', 341), ('potential', 337), ('breach', 337), ('improve', 330), ('know', 318), ('measures', 317), ('restarting', 316), ('need', 314), ('solution', 312), ('services', 307), ('outdated', 307), ('persists', 303), ('agency', 295), ('facing', 295), ('healthcare', 293), ('ensure', 291), ('cause', 289), ('various', 289), ('needed', 287), ('attempts', 286), ('resolving', 285), ('strategy', 285), ('financial', 283), ('compatibility', 281)]
Category : IT Support
[('software', 909), ('security', 660), ('tools', 636), ('analytics', 602), ('marketing', 571), ('digital', 565), ('medical', 504), ('investment', 501), ('integration', 494), ('resolve', 476), ('project', 443), ('recent', 430), ('updates', 429), ('matter', 406), ('management', 391), ('platform', 385), ('access', 385), ('guidance', 384), ('saas', 372), ('performance', 367), ('network', 348), ('restarting', 346), ('systems', 345), ('server', 321), ('enhance', 307), ('update', 305), ('steps', 300), ('devices', 298), ('strategies', 284), ('hospital', 281), ('brand', 273), ('possible', 265), ('look', 261), ('persists', 238), ('solution', 236), ('optimization', 228), ('improve', 227), ('despite', 224), ('need', 213), ('potential', 213), ('connectivity', 211), ('know', 209), ('facing', 205), ('resolving', 205), ('cause', 203), ('integrating', 201), ('agency', 200), ('attempts', 192), ('breach', 192), ('growth', 192), ('efforts', 190), ('updating', 188), ('seeking', 187), ('troubleshooting', 185), ('details', 183), ('affected', 179), ('patient', 173), ('impacting', 172), ('healthcare', 172), ('time', 172)]
Category : Customer Service
[('integration', 887), ('analytics', 874), ('investment', 873), ('security', 828), ('digital', 819), ('medical', 750), ('strategies', 740), ('software', 676), ('project', 660), ('management', 637), ('marketing', 634), ('brand', 593), ('guidance', 568), ('saas', 549), ('tools', 529), ('details', 488), ('access', 415), ('look', 415), ('platform', 414), ('enhance', 401), ('detailed', 376), ('services', 369), ('integrating', 366), ('matter', 354), ('resolve', 351), ('hospital', 350), ('systems', 349), ('interested', 342), ('growth', 341), ('seeking', 336), ('updates', 333), ('features', 323), ('recent', 321), ('engagement', 313), ('additionally', 300), ('performance', 292), ('optimization', 287), ('like', 281), ('despite', 276), ('healthcare', 267), ('reaching', 265), ('measures', 265), ('improve', 263), ('know', 263), ('solutions', 262), ('ensure', 261), ('steps', 259), ('possible', 257), ('hearing', 249), ('efforts', 248), ('potential', 243), ('solution', 243), ('learning', 229), ('need', 224), ('sensitive', 224), ('financial', 215), ('products', 214), ('time', 209), ('response', 205), ('campaign', 204)]
Category : Human Resources
[('security', 151), ('software', 146), ('access', 113), ('medical', 98), ('management', 86), ('project', 86), ('investment', 80), ('integration', 75), ('analytics', 75), ('saas', 71), ('digital', 71), ('platform', 67), ('resolve', 66), ('systems', 65), ('tools', 65), ('details', 64), ('hospital', 63), ('matter', 61), ('employee', 61), ('guidance', 61), ('recent', 59), ('strategies', 59), ('potential', 56), ('incident', 54), ('look', 53), ('marketing', 51), ('brand', 49), ('unauthorized', 46), ('efforts', 45), ('features', 45), ('possible', 45), ('breach', 44), ('update', 43), ('steps', 42), ('enhance', 42), ('optimization', 42), ('additionally', 41), ('updates', 40), ('available', 39), ('despite', 37), ('regarding', 37), ('resources', 37), ('time', 35), ('process', 34), ('protocols', 34), ('like', 33), ('measures', 32), ('troubleshooting', 32), ('restarting', 32), ('know', 32), ('cause', 31), ('ensure', 31), ('assist', 31), ('impacting', 31), ('solution', 31), ('analysis', 31), ('services', 30), ('healthcare', 30), ('resolving', 30), ('engagement', 30)]
Category : General Inquiry
[('investment', 101), ('integration', 99), ('digital', 95), ('security', 88), ('marketing', 84), ('analytics', 81), ('strategies', 76), ('enhance', 74), ('engagement', 71), ('tools', 70), ('medical', 66), ('software', 65), ('brand', 58), ('systems', 56), ('improve', 46), ('optimization', 46), ('project', 45), ('management', 41), ('platform', 40), ('despite', 40), ('recent', 39), ('potential', 38), ('performance', 37), ('current', 36), ('user', 36), ('saas', 35), ('hospital', 35), ('update', 34), ('measures', 34), ('efforts', 34), ('access', 32), ('resolve', 32), ('server', 32), ('matter', 32), ('possible', 31), ('need', 31), ('results', 31), ('audience', 31), ('overall', 29), ('growth', 29), ('time', 29), ('updates', 29), ('reaching', 28), ('steps', 28), ('cause', 27), ('network', 27), ('campaign', 27), ('believe', 27), ('outdated', 27), ('tool', 27), ('experience', 26), ('additionally', 26), ('look', 26), ('content', 25), ('seeking', 25), ('users', 25), ('resolving', 25), ('products', 24), ('visibility', 24), ('protocols', 24)]

In [129]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(max_features = 5000)

x = vectorizer.fit_transform(df['clean_text'])
y = df['category']
print("{x} ----- {y}")

{x} ----- {y}

In [130]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [131]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter = 200)
model.fit(x_train, y_train)

LogisticRegression(max_iter=200)

In [133]:
from sklearn.metrics import classification_report

y_pred = model.predict(x_test)

print(classification_report(y_test, y_pred))

                                 precision    recall  f1-score   support

           Billing and Payments       0.86      0.67      0.75       301
               Customer Service       0.38      0.35      0.37       496
                General Inquiry       1.00      0.05      0.10        37
                Human Resources       1.00      0.12      0.21        68
                     IT Support       0.43      0.23      0.30       362
                Product Support       0.38      0.41      0.40       620
          Returns and Exchanges       0.79      0.11      0.19       175
            Sales and Pre-Sales       0.79      0.09      0.16       127
Service Outages and Maintenance       0.84      0.54      0.66       161
              Technical Support       0.44      0.75      0.56       921

                       accuracy                           0.47      3268
                      macro avg       0.69      0.33      0.37      3268
                   weighted avg       0.53      0.47      0.44      3268

In [136]:
import os
os.mkdir('models')

In [137]:
import pickle
pickle.dump(model, open("models/category_model.pkl",'wb'))
pickle.dump(vectorizer,open('models/vectorizer.pkl','wb'))